return {
    cmd = { "harper-ls", "--stdio" },
    filetypes = {
        "bib",
        "gitcommit",
        "markdown",
        "org",
        "plaintex",
        "rst",
        "rnoweb",
        "tex",
        "typst",
        "pandoc",
        "quarto",
        "rmd",
        "context",
        "html",
        "xhtml",
        "mail",
        "text",
    },
}
